### ISSUE TITLE
starts incorrectly

### ISSUE THREAD

**Issue by lucidrapture** [radiatoryang/Yarn-Weaver#2]
![yarn](https://user-images.githubusercontent.com/7615846/28750179-78300b66-7497-11e7-906b-bc9c60c60881.png)

Here is a test file I made and saved as .json 

When I open the file inside YarnWeaver, the text windows "hello" followed by "bye" are displayed, and then the next click presents the choice while on "bye", like this:
![yarn2](https://user-images.githubusercontent.com/7615846/28750196-08354fd2-7498-11e7-976f-3abb0c175b9f.png)

if i understand correctly the choice should be present on the first window?

**Comment by radiatoryang** [comment]
This is an intentional YarnSpinner implementation decision, see [their Usage documentation](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/YarnSpinner-Dialogue/Usage.md#options): "When all of the lines in a node have been displayed, the dialogue system gives your game the list of available options. You then let the user choose an option, and then continue loading lines of dialogue, one at a time."

I understand it'll seem unintuitive if you're coming from Twine, but I think it's the result of Yarn's purpose as a dialogue system. By waiting until the end of a passage before displaying choices, you could, for example, "accumulate" possible choices based on scripting logic.

I think you have two options: (1) separate your passages more, and try not to do so much in one passage, or (2) if you want to offer choices in the middle of a passage, you should use the ["shortcut choice" syntax](https://github.com/thesecretlab/YarnSpinner/blob/master/Documentation/YarnSpinner-Dialogue/Usage.md#shortcut-options) instead, where you indent and type "->" for each choice... here's the example from their documentation:

	Bob: What would you like?
	-> A burger. <<if $money >= 5>>
		Bob: Nice. Enjoy!
	-> A soda. <<if $money >= 2>>
		Bob: Yum!
	-> Nothing.
	Bob: Thanks for coming!
